# Generated by Django 5.0.6 on 2024-07-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
