# Generated by Django 5.0.6 on 2024-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_receta_titulo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='cuentas.receta'),
        ),
    ]
