# Generated by Django 5.0.6 on 2024-07-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_profile_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(default='Ingredientes no especificados'),
        ),
        migrations.AddField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(default='Preparación no especificada'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='recetas/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(default='Título de la receta', max_length=100),
        ),
    ]
