# Generated by Django 5.0.6 on 2024-07-13 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_receta_valoracion_valoracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracion',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='puntuacion',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('receta', 'usuario')},
        ),
    ]
