# Generated by Django 5.0.6 on 2024-07-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_rename_autor_valoracion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='receta',
            name='total_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='valoracion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
